name: a test workflow
on:
  push:
    branches: ["test"]
      
  

jobs:
  testing-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "Running tests..."

      - name: Run tests for the second time
        run: echo "Running tests..."